apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-read
spec:
  params:
    - name: repo-url
      type: string
      description: https://github.com/simhasuraj/my_first_task
      tasks:
      - name: fetch-source
        taskRef: git-clone
        params:
        - name: url
          value: $(params.repo-url)
