apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
  workspaces:
    - name: cloned
      optional: true
  tasks:
    - name: sample-task
      taskRef:
        name: sample-task
      params:
    - name: sample-python-task
      taskRef: 
        name: sample-python-task
      params:
