apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
  workspaces:
    - name: cloned
  tasks:
    - name: sample-task
      taskRef:
        name: sample-task
      params:
      workspaces:
      - name: cloned
    - name: sample-python-task
      taskRef: 
        name: sample-python-task
      params:
      workspaces:
      - name: cloned
      runAfter:
        - sample-task
      
---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-pipeline-run
spec:
  workspaces:
    - name: cloned
      volumeClaimTemplate:
        metadata:
          name: pipeline-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  pipelineRef:
    name: sample-pipeline
