apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
  description: Read and display README file.
spec:
  workspaces:
  - name: source
  steps:
  - name: read
    image: python
    script: | 
      #!/usr/bin/env sh
      cat $github.com/simhasuraj/my_first_task/blob/main/sample.py
