apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  resources:
  steps:
    - name: sample-python-task
      image: python 
      script: |
        #!/usr/bin/env git
        git clone https://github.com/simhasuraj/my_first_task  
