apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  resources:
  steps:
    - name: sample-cloning-task
      image: python    
      script: |
        #!/usr/bin/env bash
        mkdir git
        cd git
        git clone https://github.com/simhasuraj/my_first_task
  workspaces:
  - name: cloned
    mountPath: /git/my_first_task
   
    - name: sample-python-task
      runAfter:
        - sample-cloning-task
      image: python 
      script: |
        #!/usr/bin/env bash
        python3 $(workspaces.cloned.path)/sample.py
        

        
    
          
