apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  resources:
  steps:
    - name: sample-python-task
      image: openjdk   
      script: |
        // Your First Program

        class HelloWorld 
        {
          public static void main(String[] args)
          {
            System.out.println("Hello, World!"); 
          }
        }   
