apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  resources:
  workspaces: 
    - name : cloned
  steps:
    - name: sample-cloning-task
      image: python    
      script: |
        #!/usr/bin/env bash
        mkdir git
        cd git
        git clone https://github.com/simhasuraj/my_first_task > $(workspaces.cloned.path)/file
        
---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-python-task
spec:
  params:
  resources:
  workspaces: 
    - name : cloned
  steps:
    - name: sample-python-task
      image: python    
      script: |
        #!/usr/bin/env bash
        cd $(workspaces.cloned.path)/file
        python3 sample.py
        



        
    
          
