apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  resources:
  steps:
    - name: sample-cloning-task
      image: python    
      script: |
        #!/usr/bin/env bash
        mkdir git
        cd git
        git clone https://github.com/simhasuraj/my_first_task


        
    - name: sample-python-task
      runAfter:
        - sample-cloning-task
      image: python 
      script: |
        #!/usr/bin/env bash
        python3 $(workspaces.cloned.value)/sample.py
        
  workspaces:
 - name: cloned
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: /git/my_first_task
        
    
          
