apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  resources:
  steps:
    - name: sample-cloning-task
      image: python    
      script: |
        #!/usr/bin/env bash
        mkdir git
        cd git
        git clone https://github.com/simhasuraj/my_first_task > $(workspaces.messages.path)/my_first_task
   
    - name: sample-python-task
      runAfter:
        - sample-cloning-task
      image: python 
      script: |
        #python3 sample.py
        python3 $(workspaces.message.path)/sample.py
  
    workspaces:
    - name: messages
      description: The folder where we write the message to
      mountPath: /git/

        
    
          
