apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task
spec:
  params:
  resources:
  steps:
    - name: sample-python-task
      image: python 
      run: 
        #!/usr/bin/env python3
        !git clone https://github.com/simhasuraj/my_first_task.git
        cd my_first_task
        ["python3" , "sample.py"]
          
